name: Extraer y Actualizar Datos

on:
  schedule:
    # - cron: '0 6 * * *'  # Se ejecuta todos los días a las 6:00 AM UTC
    - cron: '*/5 * * * *'  # Se ejecuta cada 5 minutos

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NLTK_DATA: /home/runner/nltk_data
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 newspaper3k supabase lxml[html_clean]

      - name: Create Data Directory
        run: mkdir -p data

      - name: Run Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NLTK_DATA: /home/runner/nltk_data
        run: python scraper.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/articles.json
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push origin main